### ISSUE TITLE
Code generation fails on .NET 6

### ISSUE THREAD

**Issue by mishun** [mvkra/protobuf-net-fsharp#23]
Some test cases throw InvalidProgramException (or even hang sometimes) under .NET 6
See pull request #22

I think I have some idea why that happens, so I'll probably add a fix in a few days

**Comment by mvkara** [comment]
Resolved by #22

**Comment by mishun** [comment]
I think also updating nuget package makes sense, since both .NET 5 and .NET Core 3.1 support ends this year and so .NET 6 is currently version to go.

**Comment by mvkara** [comment]
Package published (0.2.1) - https://www.nuget.org/packages/protobuf-net-fsharp/0.2.1
